# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoolwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published',
        ),
    ]
